kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
