apiVersion: routernetes.net/v1alpha1
kind: Router
metadata:
  name: default-router
  namespace: routernetes
spec:
  dhcp:
    startIP: "192.168.100.2"
    endIP: "192.168.100.200"
    mask: "255.255.255.0"
    leaseTime: 12h
    gateway: "192.168.100.1"
    dnsServer: "192.168.100.1"
    domain: network.lan
  dns:
    upstreamServers:
      - "8.8.8.8"
      - "8.8.4.4"
  firewall:
    outside:
      services:
      - ssh
      - http
      - https
  interfaces:
    - name: enp0s31f6
      type: ethernet
      zone: outside
      ipv4:
        method: auto
    - name: wlp61s0
      type: ethernet
      ipv4:
        method: manual
        address: 192.168.100.1/24
  osUpdates:
    enabled: true
    timezone: UTC
    day: Sun
    time: "04:00"
